// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNyKoGMqq-VD2jaodcoW414bou70i05mQ',
    appId: '1:130818726867:web:864555f1bd96226c44ad26',
    messagingSenderId: '130818726867',
    projectId: 'spotify-clone-bb119',
    authDomain: 'spotify-clone-bb119.firebaseapp.com',
    storageBucket: 'spotify-clone-bb119.firebasestorage.app',
    measurementId: 'G-59VB8QW9L9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYWwiTlYmyEKluarvlQp5t92MiJCwX1SI',
    appId: '1:130818726867:android:d7b3043f019cacbb44ad26',
    messagingSenderId: '130818726867',
    projectId: 'spotify-clone-bb119',
    storageBucket: 'spotify-clone-bb119.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJnizkc04Pnn-wqDHB0sLjZ4enTyNim9Y',
    appId: '1:130818726867:ios:6afc2f81dcebb55d44ad26',
    messagingSenderId: '130818726867',
    projectId: 'spotify-clone-bb119',
    storageBucket: 'spotify-clone-bb119.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJnizkc04Pnn-wqDHB0sLjZ4enTyNim9Y',
    appId: '1:130818726867:ios:6afc2f81dcebb55d44ad26',
    messagingSenderId: '130818726867',
    projectId: 'spotify-clone-bb119',
    storageBucket: 'spotify-clone-bb119.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNyKoGMqq-VD2jaodcoW414bou70i05mQ',
    appId: '1:130818726867:web:906203b8b37ddc6044ad26',
    messagingSenderId: '130818726867',
    projectId: 'spotify-clone-bb119',
    authDomain: 'spotify-clone-bb119.firebaseapp.com',
    storageBucket: 'spotify-clone-bb119.firebasestorage.app',
    measurementId: 'G-KYGDESNLZT',
  );
}
